### ISSUE TITLE
`iota_bundle_pow` does not assign trunk/branch transactions according to IRI

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/entangled#1008]
`iota_bundle_pow` does not assign trunk/branch transactions in the same way that IRI does. For the last transaction in the bundle, IRI [swaps](https://github.com/iotaledger/iri/blob/d4f2a50324eb8ad9a79a54f6bfb7f7089e056db9/src/main/java/com/iota/iri/service/API.java#L1450-L1455) the trunk and branch, but `iota_bundle_pow` does not. In a simpler explanation, this is what happens:

bundle: `[A, B, C]`
trunk: `D`
branch: `E`

`attachToTangle(bundle, trunk, branch, mwm)` creates a bundle that looks like this:
`A` -- trunk: `B`, branch: `D`
`B` -- trunk: `C`, branch: `D`
**`C` -- trunk: `D`, branch: `E`**
[Example bundle](https://thetangle.org/bundle/MEJFZSSDCRBZJGFTXRXNZZEYY9GFUJVTDAJJACBHTLSQKHJETDZH9ZXWEFTJQPGCJWTLBPSVIQTLTOHGA)

`iota_pow_bundle(bundle, trunk, branch, mwm)` creates a bundle that looks like this:
`A` -- trunk: `B`, branch: `D`
`B` -- trunk: `C`, branch: `D`
**`C` -- trunk: `E`, branch: `D`**
[Example bundle](https://thetangle.org/bundle/AYIDAJ9PPARTOLEYGXEBRKWANGWRQOKPD9SIOKIZVBABRLXZIDATDSBBGEZZVOPBQKC9OKGOXUXWIAGL9)

Both bundles are still valid on the network however, so this is probably a low priority issue.

**Comment by GalRogozinski** [comment]
Note that in the last row
> C -- trunk: D, branch: E

The trunk and branch are as given in the method parameters.

Think of `trunk` as the main transaction you want to give more cumulative weight to (more approvals), and `branch` as the secondary transaction.

Note that IRI prefers to add more weight to the what was specified as `trunk` in signature.

From my POV `iota_pow_bundle` swaps because for the last transaction the `trunk` and `branch` are not consistent with the parameters at the function's signature.
