### ISSUE TITLE
Use flex_trits in the structure of response and request.

### ISSUE THREAD

**Issue by oopsmonk** [iotaledger/entangled#228]
Cclient stores plain text of hashes in the structure of response and request. For the long-term, should use flex_trtis.

**Comment by oopsmonk** [comment]
@tsvisabo @thibault-martinez @ifullgaz 
Should we have the `address`, `hashes`, `bundle`, and `tag` implementation in the `common/model` first? so cclient can validate the hash using those models.

**Comment by tsvisabo** [comment]
sounds reasonable, though `bundle` is actually `bundle_hash` because `bundle` in `common/model` should be a list of transactions with functions

**Comment by oopsmonk** [comment]
Regarding with IRI doesn't accept flex_trits in the network protocol yet. the implementation of flex_trits in cclient will cause memory issues. 
Base on the low-end devices, the conversion between flex_trits will require more memory, computing power, and memory fragmentation.
The run-time increases 0.06ms in broadcasting 10 transactions at `iota_api_broadcast_transactions` on Intel Core-i5 quad-core CPU, compare to the current implementation.
I suggest fixing this issue after IRI support flex_trits.

**Comment by tsvisabo** [comment]
conversion between `flex_trit` and `trytes`?
if so, when we use only `FLEX_TRIT_ENCODING_3_TRITS_PER_BYTE`, `flex_trit` is essentially `trytes`, so calling `flex_trits_to_trytes` just use `memcpy`, in addition 0.03 ms is really negligible on 10 transactions (it would be more interesting to know the percentage in which run-time was increased)
i believe that it is better to attend this issues now because it will be more complicated in the future
