### ISSUE TITLE
IXI implementation

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/entangled#326]

**Comment by th0br0** [comment]
We do not really need IXI in cIRI, instead we should try to expose some modular hooks once the foundation is done :thinking:

**Comment by Citrullin** [comment]
It would be also really hard to implement IXI in cIRI. I mean IXI is simply Java which executes Scripts in the Javascript syntax. So, you have access to all class instances, internal APIs etc. I think the current design of IXI is also kind of dangerous, since you can change the internal behavior of IRI. But that is another topic. 

Generally a plugin-system can be interesting for some use-cases, while for others an embedded IOTA node can be interesting. This should be already possible with cIRI. With a clean and documented external API, this should not be a problem at all. (cIRI embedded server API) That is probably the modular hooks, I guess. I think a plugin system is not a necessity. You can also solve it with an embedded server or good external APIs. Especially the ZeroMQ API is amazing for additional application/features.

**Comment by thibault-martinez** [comment]
Won't be done.
