### ISSUE TITLE
The naming for a structure object. 

### ISSUE THREAD

**Issue by oopsmonk** [iotaledger/entangled#592]
It's about a structure object and a structure pointer. 
The `iota_transaction_t` is a structure pointer, but it ought to be named as a `transfer_output_p` or just `iota_transaction_t*` in general, so users don't get confused between a structure object and a structure pointer.

**Comment by thibault-martinez** [comment]
Yes ! Exactly my comment here https://github.com/iotaledger/entangled/pull/589#discussion_r238860288

In general, let's stick to the following naming convention so that's it's clear what we are handling:
- `struct type_s`
- `typedef struct type_s type_t`
- `typedef type_t * type_p` (IMHO we should not use that kind of typedef anyway)
