### ISSUE TITLE
ciri: DB files should not be tracked by git

### ISSUE THREAD

**Issue by alon-e** [iotaledger/entangled#991]
these files change when the node runs, but they are tracked by git.
so any run requires to check out the original files before switching to another branch.

https://github.com/iotaledger/entangled/tree/develop/ciri/db

reproduce:
1. start CIRI
2. gossip 1 transaction
3. stop CIRI
4. look at `git status`

**Comment by thibault-martinez** [comment]
Hi @alon-e, you're right, the reason they are currently tracked by git is because they contain the initial database schemas of cIRI. When they will be quite stable (they are already), we'll gitignore them.
Another way is to ask the user to initialize them (`sqlite3 ciri/db/ciri-mainnet.db < common/storage/sql/schema.sql`) or find a way to do it automatically with Bazel. Anyways, this is being discussed, thanks for the bump.
